### ISSUE TITLE
shell-switcher

### ISSUE THREAD

**Issue by DamienCassou** [plandes/bshell#1]
FYI, I wrote https://github.com/DamienCassou/shell-switcher a few years ago.

**Comment by plandes** [comment]
Great minds think alike!  I wrote this starting in 2014 or 2015 but I'm just recently getting all of my stuff on github to share with others.

Any ideas on combining the projects?  Looks like there is a lot of overlap.

**Comment by DamienCassou** [comment]
I don't actively do anything on shell-switcher. It works fine for me. Please steal everything you want. If you think shell-switcher has been completely replaced by bshell, I will just mark shell-switcher as deprecated and switch to bshell.

**Comment by plandes** [comment]
I'm currently spiffying it up a bit and working on it here and there but it pretty much will stay as it is.  There will be a little more documentation and functionality here and there to do things.

In terms of linking to me and deprecating your own--totally up to you.  I think someone needs to use both to find that overlap (if it's even worth it).  Might as well keep it out there so people can choose--but again do what you want.

Thanks Damien!
